### ISSUE TITLE
Roadmap for preliminary stages

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/grad-course#2]
- [x]  Write to the proposal for UofT [Dr. Popovic et al.] and add the argument about sustainability, and get the date of the course offering etc. (#1)
- [ ] Determine timeline (deadlines for syllabus, course etc.)
    - push for course to be in Winter 2020
- [ ] plan the lesson topics to cover (see for previous discussion https://github.com/UofTCoders/council/issues/286)
    - [ ] marking components 
- [ ] Plan guest lectures? e.g. fMRI imaging analyses, biophysical models, etc. (in the second half of the semester when working on projects)
- [ ] Make course website with jekyll? see #7
